### PR TITLE
Update harbour-exrates-zh_CN.ts

### PR DESCRIPTION
**Pull request by dashinfantry**

### CODE REVIEW

**Comment by Sikarjan** [comment]
I saw your comment on Harbour. Your translation was added to the app. Does it not work? If so please open an issue.

**Comment by dashinfantry** [comment]
It is still  old translation .
--
傳送自 Android 版 myMail 星期六, 15 6月 2019, 01:44上午 +08:00 寄件人 Sikarjan  notifications@github.com :

**Comment by Sikarjan** [comment]
I went through your translation file and found some translation where the tags were not set right. I suspect that this is the reason why the new file did not work. Is it possible for you to clone the project and test the file I just uploaded?

**Comment by dashinfantry** [comment]
Yes

Sikarjan 于 2019 年 6 月 19 日 星期三 写道:
> I went through your translation file and found some translation where the tags were not set right. I suspect that this is the reason why the new file did not work. Is it possible for you to clone the project and test the file I just uploaded?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Sikarjan/harbour-exrates/pull/10#issuecomment-50325217

-- 
发送于我的Sailfish设备

**Comment by Sikarjan** [comment]
Were you able to test the latest translation file? Does it work?

**Comment by dashinfantry** [comment]
Can you send it by email as an attachment? 

Sikarjan 于 2019 年 6 月 21 日 星期五 写道:
> Were you able to test the latest translation file? Does it work?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Sikarjan/harbour-exrates/pull/10#issuecomment-50434176

-- 
发送于我的Sailfish设备

**Comment by dashinfantry** [comment]
do you in telegram group?

Sikarjan 于 2019 年 6 月 21 日 星期五 写道:
> Were you able to test the latest translation file? Does it work?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Sikarjan/harbour-exrates/pull/10#issuecomment-50434176

-- 
发送于我的Sailfish设备

**Comment by Sikarjan** [comment]
I made an new version and committed it to harbour. There should be an update tomorrow.

**Pull request merged**
